### ISSUE TITLE
Theme shown incorrectly for new users

### ISSUE THREAD

**Issue by MickenCZ** [light-200/type-master#15]
If you visit the site for the first time (localstorage is empty), the site is dark-themed but if you go into settings, it shows as light theme.
If you switch to dark it fixes itself, so perhaps just set dark as the default value in settings.

**Comment by light-200** [comment]
ahh yes @MickenCZ  I'll fix the issue

**Comment by MickenCZ** [comment]
Think it gets fixed by https://github.com/light-200/type-master/pull/17
Can I ask how do you link a pull request to an Issue?

**Comment by light-200** [comment]
you just did that by mentioning the issue no. in the pull requests description @MickenCZ
