### ISSUE TITLE
text manipulation features don't work for new users

### ISSUE THREAD

**Issue by light-200** [light-200/type-master#30]
yupp they don't work for new users

**Comment by MickenCZ** [comment]
I don't understand. What text manipulation features?
Btw. Good work on the project, it's turning out very cool.

**Comment by light-200** [comment]
Thanks for showing interest in the project.

### Text manipulation features: 
- small case mode 
- no punctuation mode 

![image](https://user-images.githubusercontent.com/44830619/150919184-b43463fd-89b9-4703-95e7-a5fd2539f200.png)

> and should set the same email in github and git config, that'll make sure that your contributions to the projects do count

**Comment by light-200** [comment]
the feature works fine now
