### ISSUE TITLE
total words and typed words counter should be changed to be vice-versa

### ISSUE THREAD

**Issue by lugenx** [light-200/type-master#33]
Let's say I typed 2 of 10 words.  2/10 would be more understandable and mathematically correct instead of 10/2.

**Comment by light-200** [comment]
Yupp you're right, Since this needs changes in the js file i'll work on this issue

**Comment by lugenx** [comment]
I don't mind taking care of this one, too, if you have a lot to do.

**Comment by light-200** [comment]
No its fine, actually it'll require us to build the project after making changes and that'll create some problems from your end cause because of the api credentials

**Comment by light-200** [comment]
ahh I don't think it looks good this way, should I revert it back

**Comment by lugenx** [comment]
This way makes more sense for me, but it might be subjective. Maybe you will like it if you make "typed word count" two digits instead of one? `01/12, 02/12 ... 11/12` instead of `1/12, 2/12 ... 11/12 ` ? You can try or change directly to the previous version, up to you.
