### ISSUE TITLE
speed indicator and word counter needs some clarification

### ISSUE THREAD

**Issue by lugenx** [light-200/type-master#34]
Labeling each of them would work against the simplicity of the UI. But this issue can be solved with mouse hover text or maybe for only the "speed indicator" barely visible WPM after the number would look good.

**Comment by light-200** [comment]
yeah this can be done easily with css, i've already added hover effect for the next button, if you want you can work on this issue i'll assign it to you

**Comment by lugenx** [comment]
sure, i can work on it
